[build]
  # This is the directory Netlify will deploy as your static site
  publish = "public"
  
  # This is the directory where Netlify will find your serverless functions
  functions = "netlify/functions"

[functions."extract"]
  timeout = 20